const FILTERS = [
  { id: "typical",
    label: "Typical",
    filters: [] },
  { id: "lowacuity",
    label: "Low Acuity",
    link: "https://en.wikipedia.org/wiki/Visual_acuity",
    slider: { min: 0, max: 50, step: 1, value: 20,
              argFunc: v => [["triangleBlur", [v]]] } },
  { id: "lowcontrast",
    label: "Contrast Loss",
    link: "https://en.wikipedia.org/wiki/Contrast_(vision)",
    slider: { min: 0, max: 90, step: 1, value: 50,
              argFunc: v => [["brightnessContrast", [0, v/100 * -1]]] } },
  { id: 'protanomaly',
    label: "Protanomaly",
    link: "http://www.color-blindness.com/protanopia-red-green-color-blindness/",
    slider: { min: 0, max: 1, step: 0.01, value: 0.5,
              argFunc: v => [['colorMatrix', [[1 - v * 0.433, v * 0.433, 0, 0, 0,
                                               v * 0.558, 1 - v * 0.558, 0, 0, 0,
                                               0, v * 0.242, 1 - v * 0.242, 0, 0,
                                               0, 0, 0, 1, 0]]]] } },
  { id: 'deuteranomaly',
    label: "Deuteranomaly",
    link: "http://www.color-blindness.com/deuteranopia-red-green-color-blindness/",
    slider: { min: 0, max: 1, step: 0.01, value: 0.5,
              argFunc: v => [['colorMatrix', [[1 - v * 0.375, v * 0.375, 0, 0, 0,
                                               v * 0.7, 1 - v * 0.7, 0, 0, 0,
                                               0, v * 0.3, 1 - v * 0.3, 0, 0,
                                               0, 0, 0, 1, 0]]]] } },
  { id: 'tritanomaly',
    label: "Tritanomaly",
    link: "http://www.color-blindness.com/tritanopia-blue-yellow-color-blindness/",
    slider: { min: 0, max: 1, step: 0.01, value: 0.5,
              argFunc: v => [['colorMatrix', [[1 - v * 0.05, v * 0.05, 0, 0, 0,
                                               0, 1 - v * 0.567, v * 0.567, 0, 0,
                                               0, v * 0.475, 1 - v * 0.475, 0, 0,
                                               0, 0, 0, 1, 0]]]] } }
];
