const FILTERS = [
  { id: "typical",
    label: "Typical",
    filters: [] },
  { id: "lowacuity",
    label: "Low Acuity",
    link: "https://en.wikipedia.org/wiki/Visual_acuity",
    slider: { min: 5, max: 50, step: 1, value: 15,
              argFunc: v => [["triangleBlur", [v]]] } },
  { id: "lowcontrast",
    label: "Contrast Loss",
    link: "https://en.wikipedia.org/wiki/Contrast_(vision)",
    slider: { min: 10, max: 90, step: 1, value: 50,
              argFunc: v => [["brightnessContrast", [0, v/100 * -1]]] } },
  { id: 'protanomaly',
    label: "Protanomaly",
    link: "http://www.color-blindness.com/protanopia-red-green-color-blindness/",
    filters: [['colorMatrix', [[0.817, 0.183, 0, 0, 0,
                                0.333, 0.667, 0, 0, 0,
                                0, 0.125, 0.875, 0, 0,
                                0, 0, 0, 1, 0]]]] },
  { id: 'deuteranomaly',
    label: "Deuteranomaly",
    link: "http://www.color-blindness.com/deuteranopia-red-green-color-blindness/",
    filters: [['colorMatrix', [[0.8, 0.2, 0, 0, 0,
                                0.258, 0.742, 0, 0, 0,
                                0, 0.142, 0.858, 0, 0,
                                0, 0, 0, 1, 0]]]] },
  { id: 'tritanomaly',
    label: "Tritanomaly",
    link: "http://www.color-blindness.com/tritanopia-blue-yellow-color-blindness/",
    filters: [['colorMatrix', [[0.967, 0.033, 0, 0, 0,
                                0, 0.733, 0.267, 0, 0,
                                0, 0.183, 0.817, 0, 0,
                                0, 0, 0, 1, 0]]]] },
  { id: 'protanopia',
    label: "Protanopia",
    link: "http://www.color-blindness.com/protanopia-red-green-color-blindness/",
    filters: [['colorMatrix', [[0.567, 0.433, 0, 0, 0,
                                0.558, 0.442, 0, 0, 0,
                                0, 0.242, 0.758, 0, 0,
                                0, 0, 0, 1, 0]]]] },
  { id: 'deuteranopia',
    label: "Deuteranopia",
    link: "http://www.color-blindness.com/deuteranopia-red-green-color-blindness/",
    filters: [['colorMatrix', [[0.625, 0.375, 0, 0, 0,
                                0.7, 0.3, 0, 0, 0,
                                0, 0.3, 0.7, 0, 0,
                                0, 0, 0, 1, 0]]]] },
  { id: 'tritanopia',
    label: "Tritanopia",
    link: "http://www.color-blindness.com/tritanopia-blue-yellow-color-blindness/",
    filters: [['colorMatrix', [[0.95, 0.05, 0, 0, 0,
                                0, 0.433, 0.567, 0, 0,
                                0, 0.475, 0.525, 0, 0,
                                0, 0, 0, 1, 0]]]] },
  { id: 'achromatopsia',
    label: "Achromatopsia",
    link: "http://www.achromatopsia.info/color-blindness/",
    filters: [['colorMatrix', [[0.299, 0.587, 0.114, 0, 0,
                                0.299, 0.587, 0.114, 0, 0,
                                0.299, 0.587, 0.114, 0, 0,
                                0, 0, 0, 1, 0]]]] },
  { id: 'achromatomaly',
    label: "Achromatomaly",
    link: "http://www.achromatopsia.info/color-blindness/",
    filters: [['colorMatrix', [[0.618, 0.32, 0.062, 0, 0,
                                0.163, 0.775, 0.062, 0, 0,
                                0.163, 0.32, 0.516, 0, 0,
                                0, 0, 0, 1, 0]]]] }
];
